name: BuildOnTag
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo

      - uses: docker/setup-buildx-action@v3
        name: Setup Docker

      - uses: docker/login-action@v3
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        name: Docker Build and Push
        with:
          push: true
          tags: baopdt/keycloak-bundid-simulator:${{ github.ref_name }}

