name: CI
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo

      - uses: docker/setup-buildx-action@v3
        name: Setup Docker

      - uses: docker/build-push-action@v6
        if: github.ref != 'refs/heads/main'
        name: Docker Build only
        with:
          push: false
          tags: baopdt/keycloak-bundid-simulator:${{ github.run_number }}

